### ISSUE TITLE
Custom components for message 

### ISSUE THREAD

**Issue by no-1ne** [chatscope/chat-ui-kit-react#2]
Hello thank you for sharing your work...

Coming to the issue/feature request, currently message seems to take only string, it would be nice to add custom components like image, video file attachments etc something like this https://chatui.io/components/file-card

**Comment by supersnager** [comment]
Hello @startupgurukul thank you for your feedback.

We have this feature on our roadmap.
I'd like to hear from you, what approach would be better (and why)?

1. Dedicated component for each kind of message e.g. <ImageMessage />, <FileMessage />
2. One parametrized <Message /> component

**Comment by startupgurukul** [comment]
Thank you for the reply. 

Keeping message structure fixed with keys: type & payload based on type have rendering logic. Few message types like  image video and file can be handled by library still give an option to customise for users..

For example , 
type: image and payload: path to image 
type: text and payload: message text
type: video, file and payload: path

This keeps message structure simple and based on type of message render components accordingly this enables users to extend it to any type of message they like 

Here is how alibabas chat ui handles it

`const initialMessages = [
  {
    type: 'text',
    content: { text: 'message text' },
    user: { avatar: '//gw.alicdn.com/tfs/TB1DYHLwMHqK1RjSZFEXXcGMXXa-56-62.svg' },
  },
  {
    type: 'image',
    content: {
      picUrl: '//img.alicdn.com/tfs/TB1p_nirYr1gK0jSZR0XXbP8XXa-300-300.png',
    },
  },
];`

    switch (type) {
      case 'text':
        return <Bubble content={content.text} />;
      case 'image':
        return (
          <Bubble type="image">
            <img src={content.picUrl} alt="" />
          </Bubble>
        );
      default:
        return null;
    }
  
Source: https://chatui.io/components/chat

**Comment by supersnager** [comment]
@startupgurukul Thank you for your explains. 
I will add support for new kind of messages. This will be probably divided into few small update steps.

First the **&lt;Message /&gt;** component should be modified to allow to pass any content as children, or from model.content property  - for any custom content messages.
Note to myself: add **&lt;Message.Content /&gt;** Component.
For backward compatiblity current message type should have default set to _"text"_ or _"default"_ (or maybe _"html"_ because now it uses [dangerouslysetinnerhtml](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) internally)
Maybe: new **&lt;Message.Content /&gt;** component should be typed instead of **&lt;Message /&gt;**?

Next add predefined components for common types like image, video, etc

**Comment by GhazanfarKhan** [comment]
When are you releasing this feature @supersnager ?

**Comment by supersnager** [comment]
@GhazanfarKhan Today/tommorow depending on your timezone ;)

**Comment by supersnager** [comment]
32439f703361ac951522f8892a01982b8e16ccf8
https://github.com/chatscope/chat-ui-kit-react/releases/tag/v1.1.0

I will add some documentation later.

**Comment by startupgurukul** [comment]
Awesome and thank you :)

**Comment by GhazanfarKhan** [comment]
Hi, Can you add documentation and few example for this new feature.

**Comment by GhazanfarKhan** [comment]
Awesome work.

**Comment by supersnager** [comment]
Added some examples to Storybook:
https://chatscope.io/storybook/react/?path=/docs/components-message--html-content
https://chatscope.io/storybook/react/?path=/docs/components-message--text-content
https://chatscope.io/storybook/react/?path=/docs/components-message--image-content
https://chatscope.io/storybook/react/?path=/docs/components-message--custom-content

**Comment by startupgurukul** [comment]
it would be perfect if there is an onclick listener for message (in this case image, video in future when added)

**Comment by supersnager** [comment]
@startupgurukul I will add it.
