### ISSUE TITLE
sending links in message component

### ISSUE THREAD

**Issue by Rushsoul** [chatscope/chat-ui-kit-react#5]
when i copy and paste some link in message component , by default it is managed as string, it will be really helpful  if the message component cannot convert them to string and send them as it is.

**Comment by supersnager** [comment]
@Rushsoul What exactly do you mean by "send them as it is"?
Do you want to get DOMTree from contentediable div as a onSend callback param? If so, what do you want to achieve by this?

**Comment by startupgurukul** [comment]
May be they want to copy image and paste it

**Comment by supersnager** [comment]
@startupgurukul I'dont know. I'm waiting for a reply from @Rushsoul :)

**Comment by Rushsoul** [comment]
i am sorry that i haven't replied, i came out from the organization so , i don't know weather it is solved or not there.

**Comment by Rushsoul** [comment]
> @startupgurukul I'dont know. I'm waiting for a reply from @Rushsoul :)

i will tell u the problem, lets se in all other message applications when we paste some link and send in chat, it will be sent as link only , i mean receiver no need to copy that link, by just clicking on it, it will open that link in chrome.

**Comment by supersnager** [comment]
@Rushsoul Ok, I understand now what you want to achieve.
But now in onSend callback you are getting innerHTML of message input.
So if user copy a link from notepad, or from website by choosing "copy link address" from right-click context menu, this link is copied to buffer as clear text.
When user paste this link to message input, this is also pasted as clear text without html "A" tag and you will get it in callback also as clear text.

In other case when user mark some linked text on website and do CTRL+C on keyboard this is copied as HTML to buffer.
When user paste this link to message input, this is pasted as html code with A tag and you will get it in callback as html.

I think, you are talking about first case. But it's up to you to process message received as a clear text, find link in it and wrap this link in html A tag. 
This library is UI library and has nothing to do with text processing.

Moreover you should always sanitize all pasted content, because it's potentialy dangerous (it can contains dangerous scripts, or it just might ruin your layout).
Please _never send_ direct html without sanitization to other user.

And one more important thing:
When you send copied html link directly without any processing, you don't know what you send. So if this link have target="_self" when your remote user click on this link it will be opened in the same browser window, so your chat application will gone. This is probably not expected behaviour :)

That's why you should always keep an eye on what you send and display.
