### ISSUE TITLE
Scroll does not stick to bottom when loading images

### ISSUE THREAD

**Issue by p-Jimenez** [chatscope/chat-ui-kit-react#64]
Overall the MessageList component works pretty great. When set autoScrollToBottomOnMount, the list starts at the bottom but when the images load from a URL it keeps the scroll position (at least when using custom Message component). Any solution/workaround for this?

**Comment by supersnager** [comment]
Hi @p-Jimenez, thanks for the question.

This is because **&lt;MessageList /&gt;** doesn't know something inside has changed.

I think it can be solved in two ways:
1. Set explicit height of the image
or:
2. Call the scrollToBottom() method of the **&lt;MessageList /&gt;** component in the onload event of the image

How to use  scrollToBottom: https://chatscope.io/storybook/react/?path=/docs/components-messagelist--scroll-to-bottom
