### ISSUE TITLE
Custom Img for avatar

### ISSUE THREAD

**Issue by sbue** [chatscope/chat-ui-kit-react#8]
Hello all, I'd like to be able to use my own Img component instead of Avatar

I use Antd Avatar (https://ant.design/components/avatar/) but I cannot pass this into a <Conversation>. For some reason, Conversation is configured to only work with <Avatar>, which makes my component disappear

**Comment by sbue** [comment]
Looking at the code, I see there's an allowedChildren restriction.

https://github.com/chatscope/chat-ui-kit-react/blob/1ef2f75f882654ce7868afe34677e65e8784c2e3/src/components/Conversation/Conversation.jsx#L89

Is there a reason for this?

**Comment by supersnager** [comment]
@sbue Container components like Conversation, ChatContainer, etc must know where to place their child components, and how to layout them.
That's why there is allowedChildren constraint.
However, you can use any component instead of allowed.
Please check this recipe how to do it:  https://chatscope.io/storybook/react/?path=/story/documentation-recipes--page#changing-component-type-to-allow-place-it-in-container-slot

Also please read my last comments here: https://github.com/chatscope/chat-ui-kit-react/issues/7#issuecomment-766789857
