### ISSUE TITLE
Add onHover/onClick to Message component

### ISSUE THREAD

**Issue by j-krl** [chatscope/chat-ui-kit-react#81]
Just want to say thanks for this awesome library. Has saved me so much work on not having to build my own components. I've also found it to be very well made.

I'm requesting the simple feature of adding an onHover and onClick to the message component. I would like to reveal the message headers and footers with the timestamp only when they are clicked or hovered, similar to Facebook messenger.

**Comment by supersnager** [comment]
@j-krl Thanks for your kind words, I'm glad you like the library :smile: 

These methods are already there:

![image](https://user-images.githubusercontent.com/6375504/211140801-b546d8f6-f6c2-4b3a-83df-cf14d70a7175.png)

All not documented properties in components are passed down to the main HTML element of the component (unless the documentation state directly otherwise).
So the ```onClick``` callback added to the ```<Message />``` component will be assigned to the following HTML element:
```html
<section class="cs-message"></section>
```

**Comment by j-krl** [comment]
Should have thought of that. Thanks for the quick response

**Comment by j-krl** [comment]
@supersnager looking into this more and it's still not as easy as it seems like it should be. When the Message position attribute is not "first" or "single", all of the header's child elements are also hidden by default. So even if I add an onClick that reveals my header, anything contained in the header is still hidden (in my case, specifically the sentTime), and I don't easily have access to those elements.

Perhaps this is a different issue about only allowing headers on Messages with certain positions at this point, so if you'd like me to open a new issue I can do that.

Really what would be ideal is the behaviour of Facebook Messenger. onHover on desktop, the header is revealed as a tooltip. But on mobile the onClick just reveals the header.

**Comment by supersnager** [comment]
@j-krl Please check if this answer helps you: https://github.com/chatscope/chat-ui-kit-styles/issues/2
